
#ifndef _INIT_H
#define _INIT_H

//Подключаемые библиотеки...
#include <stm32f30x.h>		//Библиотека CMSIS

//Прототипы функций...
//void initRCC(void); 		//Инициализация RCC...
void init_GPIO(void); 		//Инициализация GPIO...
//void initUSART1(void); 	//Инициализация USART1...
//void initSPI1(void); 		//Инициализация SPI1...
//void initNVIC(void); 		//Инициализация NVIC...
//void initEXTI(void); 		//Инициализация EXTI...


#endif //_INIT_H
